//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescriptions
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<System.DateTime> DatePrescribed { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
